pipeline:
  name: Maven
  identifier: Maven
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: Git_RK
        repoName: MaveWebAppsOne1
        build:
          type: branch
          spec:
            branch: master
  stages:
    - stage:
        name: Test_build
        identifier: Test_build
        template:
          templateRef: Maven_test_template
          versionLabel: "1"
          gitBranch: master
